
import { VibeApp, Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    explore: 'Explore',
    topics: 'Topics',
    docs: 'Documentation',
    join: 'Join the Hub',
    nav: 'Navigation',
    allApps: 'All Applications',
    submit: 'Submit Vibe App',
    headerTitle: 'Explore Vibe-Coded Apps',
    headerDesc: 'List of Applications utilizing AI and vibe coding.',
    searchPlaceholder: "Type your idea (e.g., 'help me manage my diet')",
    searchBtn: 'AI Search',
    clear: 'Clear',
    colName: 'App Name',
    colSummary: 'Summary',
    colTags: 'Tags',
    colCreator: 'Creator',
    colSource: 'Source',
    total: 'Total',
    updated: 'Last Updated',
    formTitle: 'Submit Your Vibe App',
    formLabelName: 'App Name',
    formLabelUrl: 'Threads/GitHub Post URL',
    formVerify: 'Verification Screenshot',
    formVerifyDesc: 'Upload a screenshot showing your username as the creator.',
    formConfirm: 'I confirm that I am the individual displayed in the screenshot.',
    cancel: 'Cancel',
    submitBtn: 'Submit App',
    verifying: 'Verifying...',
    successTitle: 'Submission Received',
    successDesc: 'Verification is in progress.',
    closedSource: 'CLOSED SRC'
  },
  'zh-TW': {
    explore: '瀏覽',
    topics: '主題',
    docs: '文件',
    join: '加入中心',
    nav: '導航',
    allApps: '所有應用',
    submit: '提交應用',
    headerTitle: '探索 Vibe-Coded 應用',
    headerDesc: 'AI 與 Vibe Coding 應用程式列表。',
    searchPlaceholder: "輸入您的想法（例如：'幫助我管理飲食'）",
    searchBtn: 'AI 搜尋',
    clear: '清除',
    colName: '名稱',
    colSummary: '摘要',
    colTags: '標籤',
    colCreator: '創作者',
    colSource: '來源',
    total: '總計',
    updated: '最後更新',
    formTitle: '提交您的應用',
    formLabelName: '應用名稱',
    formLabelUrl: 'Threads/GitHub 貼文網址',
    formVerify: '驗證截圖',
    formVerifyDesc: '上傳顯示您作為創作者的使用者名稱截圖。',
    formConfirm: '我確認我是截圖中顯示的人員並擁有該應用的權利。',
    cancel: '取消',
    submitBtn: '提交',
    verifying: '驗證中...',
    successTitle: '提交成功',
    successDesc: '驗證正在進行中。',
    closedSource: '未開源'
  },
  'zh-CN': {
    explore: '浏览',
    topics: '主题',
    docs: '文档',
    join: '加入中心',
    nav: '导航',
    allApps: '所有应用',
    submit: '提交应用',
    headerTitle: '探索 Vibe-Coded 应用',
    headerDesc: '精选由 AI 辅助“Vibe Coding”开发的应用程序。发现能在几分钟內解决实际问题的工具。',
    searchPlaceholder: "输入您的想法（例如：'帮助我管理饮食'）",
    searchBtn: 'AI 搜索',
    clear: '清除',
    colName: '名称',
    colSummary: '摘要',
    colTags: '标签',
    colCreator: '创作者',
    colSource: '来源',
    total: '总计',
    updated: '最后更新',
    formTitle: '提交您的应用',
    formLabelName: '应用名称',
    formLabelUrl: 'Threads/GitHub 帖子链接',
    formVerify: '验证截图',
    formVerifyDesc: '上传显示您作为创作者的用户名截图。',
    formConfirm: '我确认我是截图中显示的个人并拥有该应用权利。',
    cancel: '取消',
    submitBtn: '提交',
    verifying: '验证中...',
    successTitle: '提交成功',
    successDesc: '验证正在进行中。',
    closedSource: '未开源'
  }
};

export const APPS_DATA: VibeApp[] = [
  // Productivity & Tools
  { id: '1', name: 'Immersive Translate', summary: 'Bilingual web/PDF translation keeping original layout.', tags: ['Browser Ext'], creator: 'Owen', category: 'Productivity & Tools', githubUrl: 'https://github.com/immersive-translate' },
  { id: '2', name: 'ThinkAny', summary: 'AI search engine with mind map visualization.', tags: ['AI Search'], creator: 'Lidang', category: 'Productivity & Tools' },
  { id: '3', name: 'BiBiGPT', summary: 'One-click summary for Bilibili/YouTube videos.', tags: ['AI Summary'], creator: 'JimmyWang', category: 'Productivity & Tools' },
  { id: '4', name: 'Podwise', summary: 'AI transcription and mind mapping for podcasts.', tags: ['Knowledge'], creator: 'Podwise Team', category: 'Productivity & Tools' },
  { id: '5', name: 'Memo Card', summary: 'Turn text into aesthetic shareable images.', tags: ['Social Tool'], creator: '1c7', category: 'Productivity & Tools' },
  { id: '6', name: 'OpenCat', summary: 'Native iOS/macOS client for ChatGPT/LLMs.', tags: ['AI Client'], creator: 'Baye', category: 'Productivity & Tools' },
  { id: '7', name: 'Chatbox', summary: 'Desktop app for managing LLM chats locally.', tags: ['AI Client'], creator: 'Bin', category: 'Productivity & Tools', githubUrl: 'https://github.com/Bin-Huang/chatbox' },
  { id: '8', name: 'Bob', summary: 'macOS translation and OCR tool.', tags: ['Utility'], creator: 'Ripperhe', category: 'Productivity & Tools' },
  { id: '9', name: 'Snipaste', summary: 'Powerful screenshot and pinning tool.', tags: ['Utility'], creator: 'Liu Yue', category: 'Productivity & Tools' },
  { id: '10', name: 'HapiGo', summary: 'Spotlight replacement and launcher for macOS.', tags: ['Productivity'], creator: 'HapiGo Team', category: 'Productivity & Tools' },
  { id: '11', name: 'Cubox', summary: 'Cross-platform bookmark and read-later service.', tags: ['Knowledge'], creator: 'Cubox Team', category: 'Productivity & Tools' },
  { id: '12', name: 'Heptabase', summary: 'Visual note-taking for complex learning.', tags: ['Knowledge'], creator: 'Alan Chan', category: 'Productivity & Tools' },
  { id: '13', name: 'Flomo', summary: 'Minimalist card-style note-taking.', tags: ['Notes'], creator: 'Light', category: 'Productivity & Tools' },
  { id: '14', name: 'MarkList', summary: 'Todo list that works like a markdown editor.', tags: ['Productivity'], creator: 'Indie Dev', category: 'Productivity & Tools' },
  { id: '15', name: 'Sorted³', summary: 'Hyper-scheduled calendar and task manager.', tags: ['Schedule'], creator: 'StaySorted', category: 'Productivity & Tools' },
  { id: '16', name: 'CleanShot X', summary: '(HK/Intl team) Ultimate screen capturing tool.', tags: ['Utility'], creator: 'MTW', category: 'Productivity & Tools' },
  
  // Design & Creative
  { id: '17', name: 'PixPin', summary: 'Screenshot and long-scroll capture tool.', tags: ['Design'], creator: 'PixPin Team', category: 'Design & Creative' },
  { id: '18', name: 'ShotEasy', summary: 'Create professional mockups from screenshots.', tags: ['Design'], creator: '1c7', category: 'Design & Creative' },
  { id: '19', name: 'VectorHub', summary: 'Search engine for free vector icons/assets.', tags: ['Assets'], creator: 'Vibe Dev', category: 'Design & Creative' },
  { id: '20', name: 'Pico', summary: 'Simple image editor for adding frames/backgrounds.', tags: ['Image Tool'], creator: 'Indie Dev', category: 'Design & Creative' },
  { id: '21', name: 'Moshimo', summary: 'Retro-style photo editor and filters.', tags: ['Photography'], creator: 'Moshimo Team', category: 'Design & Creative' },
  { id: '22', name: 'Varlens', summary: 'Pro-level DSLR camera app for iPhone.', tags: ['Photography'], creator: 'Varlens Team', category: 'Design & Creative' },
  { id: '23', name: 'MOZE', summary: 'Beautiful personal finance and expense tracking.', tags: ['Finance'], creator: 'Moze Team', category: 'Design & Creative' },
  { id: '24', name: 'QingQue', summary: 'Traditional Chinese color palette generator.', tags: ['Design'], creator: 'Indie Dev', category: 'Design & Creative' },
  { id: '25', name: 'Grid Diary', summary: 'Journaling via structured grid templates.', tags: ['Journal'], creator: 'Sumi', category: 'Design & Creative' },
  { id: '26', name: 'Lake', summary: 'Coloring books for relaxation (iPad).', tags: ['Art'], creator: 'Lake Team', category: 'Design & Creative' },

  // AI & Experimental
  { id: '27', name: 'Hayo', summary: 'All-in-one AI chat and image generation hub.', tags: ['AI Platform'], creator: 'Hayo Team', category: 'AI & Experimental' },
  { id: '28', name: 'ChatHub', summary: 'Use multiple chatbots (GPT, Bing, Bard) simultaneously.', tags: ['AI Tool'], creator: 'Vibe Dev', category: 'AI & Experimental' },
  { id: '29', name: 'Monica', summary: 'AI copilot extension for any webpage.', tags: ['Browser Ext'], creator: 'Monica Team', category: 'AI & Experimental' },
  { id: '30', name: 'Glarity', summary: 'Summarize Google search results and YouTube.', tags: ['AI Summary'], creator: 'Glarity Team', category: 'AI & Experimental' },
  { id: '31', name: 'Tome', summary: '(Popular usage in CN) AI storytelling slides.', tags: ['AI Preso'], creator: 'Tome Team', category: 'AI & Experimental' },
  { id: '32', name: 'Gamma', summary: '(Popular usage in CN) AI presentation generator.', tags: ['AI Preso'], creator: 'Gamma Team', category: 'AI & Experimental' },
  { id: '33', name: 'LobeChat', summary: 'Open-source, high-performance chat framework.', tags: ['AI Dev'], creator: 'LobeHub', category: 'AI & Experimental', githubUrl: 'https://github.com/lobehub/lobe-chat' },
  { id: '34', name: 'FastGPT', summary: 'Knowledge base Q&A system based on LLMs.', tags: ['AI Dev'], creator: 'Labring', category: 'AI & Experimental', githubUrl: 'https://github.com/labring/FastGPT' },
  { id: '35', name: 'Dify', summary: 'LLM app development platform.', tags: ['AI Infra'], creator: 'Dify Team', category: 'AI & Experimental', githubUrl: 'https://github.com/langgenius/dify' },
  { id: '36', name: 'Flowith', summary: 'AI workflow automation canvas.', tags: ['AI Tool'], creator: 'Flowith Team', category: 'AI & Experimental' },

  // Lifestyle & Niche
  { id: '37', name: 'OffScreen', summary: 'Screen time tracker to reduce phone addiction.', tags: ['Wellness'], creator: 'Luolei', category: 'Lifestyle & Niche' },
  { id: '38', name: 'Focus', summary: 'Pomodoro timer for Apple devices.', tags: ['Focus'], creator: 'Master', category: 'Lifestyle & Niche' },
  { id: '39', name: 'Moon FM', summary: 'Minimalist podcast player with sleek UI.', tags: ['Audio'], creator: 'Saqqu', category: 'Lifestyle & Niche' },
  { id: '40', name: 'ServerCat', summary: 'Monitor server status and SSH client on iOS.', tags: ['Dev Tool'], creator: 'Baye', category: 'Lifestyle & Niche' },
  { id: '41', name: 'JSBox', summary: 'Run JavaScript natively on iOS for automation.', tags: ['Dev Tool'], creator: 'Zhong颖', category: 'Lifestyle & Niche' },
  { id: '42', name: 'Price Tag', summary: 'App price tracking and discovery.', tags: ['Shopping'], creator: 'Price Tag', category: 'Lifestyle & Niche' },
  { id: '43', name: 'Wolai', summary: 'Notion-like block-based productivity suite.', tags: ['Notes'], creator: 'Wolai Team', category: 'Lifestyle & Niche' },
  { id: '44', name: 'Effie', summary: 'Minimalist writing environment for thinkers.', tags: ['Writing'], creator: 'Li Song', category: 'Lifestyle & Niche' },
  { id: '45', name: 'Xmind', summary: '(HK/CN) Famous mind mapping software.', tags: ['Brainstorm'], creator: 'Xmind Ltd', category: 'Lifestyle & Niche' },
  { id: '46', name: 'TickTick', summary: '(CN Origin) Global task management giant.', tags: ['Tasks'], creator: 'TickTick Team', category: 'Lifestyle & Niche' },
  { id: '47', name: 'Fingertip', summary: 'Quick launcher and calculator for mouse.', tags: ['Utility'], creator: 'Indie Dev', category: 'Lifestyle & Niche' },
];
